"""Add like and dislike tracking

Revision ID: c9daae032e82
Revises: 
Create Date: 2025-03-20 14:57:57.033622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9daae032e82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_transaction')
    with op.batch_alter_table('trading_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislikes_count', sa.Integer(), nullable=True))
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('likes')
        batch_op.drop_column('dislikes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislikes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('dislikes_count')
        batch_op.drop_column('likes_count')

    op.create_table('financial_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
